# 出力ファイルパス
output_file: "/ws/src/data_matomerun/icam2024/data/dwa1/ped_avoid.csv"

# 制御周波数[Hz]
hz: 10                          # ループ周波数 [Hz]

# 計測位置
start_x: 18.0  # 計測を開始するx座標 [m]
goal_x: 1.0   # 計測を終了するx座標 [m]