# 出力ファイルパス
output_file: "/ws/src/data_matomerun/icam2024/data/no_steer1/performance.csv"

# 制御周波数[Hz]
hz: 10               # ループ周波数 [Hz]

# 計測位置
start_x: 0.0  # 計測を開始するx座標 [m]
goal_x: 18.0   # 計測を終了するx座標 [m]

# 衝突判定
collision_dist: 0.5  # 衝突した判定にするロボットと歩行者の距離